services:
  flo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/flo
      - DATABASE_USERNAME=flo_user
      - DATABASE_PASSWORD=flo_pass
      - DATABASE_DDL_AUTO=update
      - DATABASE_SHOW_SQL=true
    depends_on:
      - postgres
    volumes:
      - uploads-data:/app/uploads
    networks:
      - flo-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=flo
      - POSTGRES_USER=flo_user
      - POSTGRES_PASSWORD=flo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flo-network

networks:
  flo-network:
    driver: bridge

volumes:
  postgres-data:
  uploads-data:
