spring:
  application:
    name: flo
  datasource:
    url: jdbc:postgresql://localhost:5432/flo
    username: Marta
    password: flo_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
  info:
    title: Flo E-commerce API
    description: API for managing products, categories, and orders in the Flo e-commerce system
    version: 1.0.0
    contact:
      name: Support Team
      email: support@example.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
server:
  port: 8080

telegram:
  bot-token: ''
  chat-id: ''