POST http://localhost:8080/api/products
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="product"
Content-Type: application/json

{
  "name": "таби",
  "description": "носкиДляЯпонцев",
  "categoryIds": [2],
  "price": 1000,
  "status": "ACTIVE"
}
--boundary
Content-Disposition: form-data; name="photos"; filename="photo1.jpg"
Content-Type: image/jpeg

< ./photo_2024-05-23_12-31-48.jpg
--boundary
Content-Disposition: form-data; name="photos"; filename="photo2.png"
Content-Type: image/jpeg

< ./115308.png
--boundary--


###

POST http://localhost:8080/api/products
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="product"
Content-Type: application/json

{
  "name": "таби",
  "description": "носкиДляЯпонцев",
  "categoryIds": [2],
  "price": 1000,
  "status": "ACTIVE"
}

###

GET http://localhost:8080/api/products
Accept: application/json

###

GET http://localhost:8080/api/products/6
Accept: application/json


###

DELETE http://localhost:8080/api/products/3
Accept: application/json
###

POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "ботинки"
}

###

GET http://localhost:8080/api/categories
Accept: application/json

###

DELETE http://localhost:8080/api/categories/3
Content-Type: application/json

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "customerName": "Иван Smith",
  "productIds": [1],
  "email": "ivan@example.com",
  "phone": "+7 999 123 45 67",
  "telegramUsername": "@ivan_ivanov",
  "customerComment": "Прошу доставить как можно скорее!"
}

###

GET http://localhost:8080/api/orders
Accept: application/json