POST http://localhost:8080/api/products?name=таби&description=носкиДляЯпонцев&categoryIds=2&price=1000&status=ACTIVE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photos"; filename="photo1.jpg"
Content-Type: image/jpeg

< ./photo_2024-05-23_12-31-48.jpg
--boundary
Content-Disposition: form-data; name="photos"; filename="photo2.png"
Content-Type: image/jpeg

< ./115308.png
--boundary--

###

GET http://localhost:8080/api/products/1
Accept: application/json

###

POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "ботинки"
}

###

GET http://localhost:8080/api/categories
Accept: application/json

###

GET http://localhost:8080/api/products
Accept: application/json

###